### PR TITLE
Add a README

### PR DESCRIPTION
**Pull request by ocefpaf**
Let's add a README that describes this page to disambiguate it from the other one, https://gliders.ioos.us/providers/, that is also created by this repo.

### CODE REVIEW

**Comment by MathewBiddle** [comment]
I don't know how you feel about it @ocefpaf, but I like to include instructions for how to deploy the docs locally. For example, https://github.com/ioos/mbon-docs/blob/gh-pages/README.md

**Comment by kbailey-noaa** [comment]
@ocefpaf I agree with @MathewBiddle, plus for any community members (esp in the DMAC world) who might want to suggest changes, we should add Code of Conduct info as seen in https://gist.github.com/PurpleBooth/b24679402957c63ec426

**Comment by kbailey-noaa** [comment]
@ocefpaf I agree with @MathewBiddle 's recommendation.

**Review by kbailey-noaa — CHANGES_REQUESTED** [review]
Per Matt's comment, include instructions for how to deploy the docs locally. For example, https://github.com/ioos/mbon-docs/blob/gh-pages/README.md

**Comment by ocefpaf** [comment]
> I don't know how you feel about it @ocefpaf, but I like to include instructions for how to deploy the docs locally. For example, https://github.com/ioos/mbon-docs/blob/gh-pages/README.md

Makes sense. Will to early tomorrow.

**Comment by ocefpaf** [comment]
This one should be ready for another round of reviews!

**Pull request merged**
